### ISSUE TITLE
SyntaxError: invalid token

### ISSUE THREAD

**Issue by OpenHaus** [dailymotion/dailymotion-sdk-python#8]
nosetests fail with Python 3:
# nosetests -v

Failure: SyntaxError (invalid token (dailymotion.py, line 40)) ... ERROR
# 
## ERROR: Failure: SyntaxError (invalid token (dailymotion.py, line 40))

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3.4/site-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib64/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/fabio/public_html/dailymotion-sdk-python/TestDailymotion.py", line 1, in <module>
    import dailymotion
  File "/home/fabio/public_html/dailymotion-sdk-python/dailymotion.py", line 40
    os.chmod('%s.db' % backend_file, 0600)
                                        ^
SyntaxError: invalid token

---

Ran 1 test in 0.015s

FAILED (errors=1)

**Comment by Amzani** [comment]
Hi the SDK doesn't support the Python 3 yet.
Any chance to use it with Python 2.7 ?
